CMS-149-create-help-view
KeimiLL/Club-Management-System pull request #129
Opened 2023-11-04 20:31 UTC by KeimiLL

2023-11-06 18:50 UTC, Rolero4 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.ts
> +export class HelpComponent {
Dorób może jakiś serwis do tego bo jest tu mnóstwo niepotrzebnej logiki biznesowej niezwiązanej stricte z komponentem.

2023-11-06 18:50 UTC, Rolero4 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.html
> +            <h2 class="card__headline">
Na dole jest ten sam html -> nowy komponent

2023-11-06 18:50 UTC, Rolero4 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.ts
> +    protected showWelcomeCard = true;
Jakaś jedna zmienna do przechwytywania stanu może jakiś enum lub coś

2023-11-06 18:50 UTC, Rolero4 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.ts
> +    protected currentPhoto: Photo = this.photos[this.currentPhotoIndex];
Imo useless zmienna, masz index to se po nim leć a to jest niepotrzebne

2023-11-08 18:22 UTC, Domin8668 requested changes

2023-11-08 18:22 UTC, Domin8668 commented on README.md
> +1. To start Docker containers defined in a `docker-compose.yml`` file and force a rebuild of images to ensure they are up to date before running:
Jeden backtick za dużo.
I ten opis się kompletnie mija z prawdą, flaga -V odpowiada za co innego: https://docs.docker.com/engine/reference/commandline/compose_up/#options

2023-11-08 18:22 UTC, Domin8668 commented on README.md
> +   To allow your IDE to detect frontend packages install frontend dependencies inside the `frontend/` directory using:
Czemu tu usunięta numeracja?

2023-11-08 18:22 UTC, Domin8668 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.ts
> +            this.currentPhoto = this.photos[this.currentPhotoIndex];
`this.currentPhoto = this.photos[--this.currentPhotoIndex];`?

2023-11-08 18:22 UTC, Domin8668 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.html
> +                [disabled]="!(currentPhotoIndex > 0)"
Nie lepiej odwrócić warunek, żeby nie trzeba było robić negacji?

2023-11-08 18:22 UTC, Domin8668 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.html
> +                [disabled]="!(currentPhotoIndex < photos.length)"
Podobnie tu.

2023-11-13 13:07 UTC, Domin8668 commented on README.md
> +1. To create and start Docker containers defined in a `docker-compose.yml` file. The `-V` option recreate anonymous volumes instead of retrieving data from the previous containers:
Trochę po angielskiemu, ale to sam poprawię przy okazji.

2023-11-13 13:08 UTC, Domin8668 commented on frontend/src/app/components/routes/main-view/components/settings/components/help/help.component.html
> +            [value]="((currentPhotoIndex + 1) / photos.length) * 100"
W sumie też nadmiarowy nawias tu?

2023-11-18 20:16 UTC, merged