CMS-92-add-preloader
KeimiLL/Club-Management-System pull request #78
Opened 2023-10-08 07:10 UTC by KeimiLL

2023-10-08 22:05 UTC, Rolero4 requested changes

2023-10-10 20:21 UTC, Domin8668 commented on frontend/src/app/shared/services/table.service.ts
>          return request.pipe(
Nie pamiętam dokładnie jak jest tutaj z pipe chainem, ale warto się upewnić, że spinner się wyłączy jak walnie jakiś błąd http.

2023-10-10 20:22 UTC, Domin8668 commented on frontend/src/styles/_variables.scss
> +        color: #666;
Kolorki do zmiennych.

2023-10-13 20:08 UTC, Rolero4 commented on frontend/src/app/components/routes/main-view/components/meetings/meetings.component.html
> +                    [ngClass]="{ 'button--disabled': isLoading$ | async }"
klase z scss da się globalnie dac buttonowi, żeby nie tzreba było w każdym komponencie jej dodawać

2023-10-13 20:08 UTC, Rolero4 commented on frontend/src/app/shared/components/spinner/spinner.component.ts
> +    @Input() spinnerMessage: string;
accessibility

2023-10-13 20:08 UTC, Rolero4 commented on frontend/src/app/shared/services/loader.service.ts
> +    public enableSpinner(): void {
jak jest ten setter to go użyj, 
this.isLoading = true,

2023-10-13 20:08 UTC, Rolero4 commented on frontend/src/app/components/routes/main-view/components/meetings/meetings.component.html
> +                    [ngClass]="{ 'button--disabled': isLoading$ | async }"
Tzn dać buttowi, że jeśli jest disabled to ma mieć określone style

2023-10-31 13:28 UTC, merged